name: Deploy or Destroy AWS Infrastructure with Terraform

on:
  workflow_dispatch:  # Enables manual triggers
    inputs:
      action:
        description: "Choose action: apply or destroy"
        required: true
        default: "apply"  # Default action is 'apply'
        type: choice
        options:
          - apply
          - destroy

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Terraform
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0  # Specify the Terraform version

      # Configure AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-1

      # Initialize Terraform
      - name: Terraform Init
        run: terraform init

      # Validate Terraform configuration (optional but recommended)
      - name: Terraform Validate
        run: terraform validate

      # Conditionally apply or destroy Terraform resources
      - name: Apply or Destroy Terraform Resources
        run: |
          if [ "${{ github.event.inputs.action }}" == "apply" ]; then
            terraform apply -auto-approve
          elif [ "${{ github.event.inputs.action }}" == "destroy" ]; then
            terraform destroy -auto-approve
          else
            echo "Invalid action. Please choose 'apply' or 'destroy'."
            exit 1
          fi
